#yaml配置文件支持多profile, 可根据不同profile配置参数
spring.profiles.active: dev

#日志使用log4j2, 可直接配置日志级别, 如需进一步配置日志, 可通过log4j2.xml
logging:
  level: #日志级别, 可针对不同package设置
    root: info
    com.jsits: debug
  file: sellmall.log #日志默认输出到控制台, 可输出到文件

#com.jsits.framework.core.CoreConfiguration
CoreConfiguration:
  serverId: 0
  cacheExpiration: 3600
  fileUrlPrefix: http://218.94.13.134:16000/


#Oracle数据源配置
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sellmall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  username: root
  password: yuzheng
  validationQuery: SELECT 1
  filters: stat
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  initialSize: 1
  minIdle: 10
  maxActive: 100
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 300000
  minEvictableIdleTimeMillis: 600000
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
  removeAbandoned: true
  removeAbandonedTimeout: 7200
  logAbandoned: true

spring.http.multipart: # spring 文件上传大小限制
  max-file-size: 10Mb
  max-request-size: 100Mb

imageFileService: # 图片文件服务
  trackerList:
    - 192.168.3.97:22122
  webBasePath: image
  maxFileSize: 2097152

documentFileService: # 附件文件服务
  trackerList:
    - 192.168.3.97:22122
  webBasePath: document
  maxFileSize: 10485760

---

#开发环境
spring.profiles: dev

spring.datasource:
  url: jdbc:mysql://localhost:3306/sellmall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  username: root
  password: yuzheng