var app = angular.module("myApp",[]);
app.controller("myCtrl",["$scope",function($scope){

	$scope.str = window.location.href;
	$scope.param = $scope.str.split("=")[1].split(".")[0];
	// console.log($scope.param);
	$scope.details = {
		"p1":{
			"sider":["../img/screen/p1/1.jpg","../img/screen/p1/2.jpg","../img/screen/p1/3.jpg","../img/screen/p1/4.jpg","../img/screen/p1/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"无鞋盒 漆皮女士细三角高跟鞋 171603230001 CHC",
			"price":"￥1880.00",
			"color":"#f074b4",
			"size":["36","37.5"],
			"num":"338906",
			"goosNum":"171603230001",
			"address":"意大利",
			"year":"2017",
			"fit":"女士",
			"color1":"粉色",
			"season":"秋冬新款",
			"serise":"-",
			"time":"该商品到货时间预计3-5个工作日",
			"mateirs":"皮",
			"desc":"【17秋冬】DIOR/迪奥 漆皮女士高跟鞋 171603230001 CHC无鞋盒",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p2":{
			"sider":["../img/screen/p2/1.jpg","../img/screen/p2/2.jpg","../img/screen/p2/3.jpg","../img/screen/p2/4.jpg"],
			"brand":"Dior 迪奥",
			"info":"小牛皮 男士 皮带",
			"price":"￥3480.00",
			"color":"#2A2A2A",
			"size":["100","105","90","95"],
			"num":"303055",
			"goosNum":"4166PLXJL H02G",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"男士",
			"color1":"黑色",
			"season":"-",
			"serise":"-",
			"mateirs":"小牛皮",
			"desc":" 尺码：  带体2.5   颜色：黑色  材质：小牛皮   描述：涂层帆布和黑色小牛皮，可调节带头",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p3":{
			"sider":["../img/screen/p3/1.jpg","../img/screen/p3/2.jpg","../img/screen/p3/3.jpg","../img/screen/p3/4.jpg","../img/screen/p3/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"羊皮 女士 手提包",
			"price":"￥23309.00",
			"color":"#2963E9",
			"size":["无",],
			"num":"303055",
			"goosNum":"4166PLXJL H02G",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"黑色",
			"season":"-",
			"serise":"-",
			"mateirs":"小牛皮",
			"desc":" 尺码：  带体2.5   颜色：黑色  材质：小牛皮   描述：涂层帆布和黑色小牛皮，可调节带头",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p4":{
			"sider":["../img/screen/p4/1.jpg","../img/screen/p4/2.jpg","../img/screen/p4/3.jpg","../img/screen/p4/4.jpg","../img/screen/p4/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"牛皮 女士 长钱包",
			"price":"￥989.00",
			"color":"#2A2A2A",
			"size":["无",],
			"num":"101041",
			"goosNum":"2DECH002XIS 02G_HW",
			"address":"-",
			"year":"2016",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"黑色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"三个卡位，两个插袋",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p5":{
			"sider":["../img/screen/p5/1.jpg","../img/screen/p5/2.jpg","../img/screen/p5/3.jpg","../img/screen/p5/4.jpg","../img/screen/p5/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"桑蚕丝混纺 男士 长袖针织衫",
			"price":"￥5149.00",
			"color":"#DDD091",
			"size":["S","M","L","XL","XXL"],
			"num":"200104",
			"goosNum":"533M670ZT012 802 882 _HW",
			"address":"意大利",
			"year":"2015",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"男士",
			"color1":"多色",
			"season":"-",
			"serise":"-",
			"mateirs":"桑蚕丝混纺",
			"desc":"黑色底混纺桑蚕丝材质，多色花卉图饰，袖口及下摆松紧收口设计，圆领长袖款式",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p6":{
			"sider":["../img/screen/p6/1.jpg","../img/screen/p6/2.jpg","../img/screen/p6/3.jpg","../img/screen/p6/4.jpg","../img/screen/p6/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"牛皮 男士 皮带",
			"price":"￥4010.00",
			"color":"#2A2A2A",
			"size":["85","90","95"],
			"num":"337416",
			"goosNum":"4044PLVE9-967",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"男士",
			"color1":"黑色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"尺寸：宽3.5cm 尺码：85  材质：牛皮",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p7":{
			"sider":["../img/screen/p7/1.jpg","../img/screen/p7/2.jpg","../img/screen/p7/3.jpg","../img/screen/p7/4.jpg","../img/screen/p7/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"牛皮 男士 平底鞋",
			"price":"￥5520.00",
			"color":"#474086",
			"size":["39","40","40.5","41.5"],
			"num":"337412",
			"goosNum":"3SN201XFX-965",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"男士",
			"color1":"多色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"材质：牛皮",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"p8":{
			"sider":["../img/screen/p8/1.jpg","../img/screen/p8/2.jpg","../img/screen/p8/3.jpg","../img/screen/p8/4.jpg","../img/screen/p8/5.jpg"],
			"brand":"Dior 迪奥",
			"info":"牛皮 男士 短钱包",
			"price":"￥4010.00",
			"color":"#1F1E23",
			"size":["无"],
			"num":"337411",
			"goosNum":"2NWCA127XSR-H03E",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"男士",
			"color1":"多色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"尺寸：16*12cm    材质：牛皮  描述：黑色頂級小牛皮，白色Christian Dior及藍色和桃紅色Newave印花，內部壓印「Dior」標誌",
			"story":"Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。",
			"logoBg":"../img/screen/p1/bd.jpg"
		},
		"a1":{
			"sider":["../img/screen/a1/1.jpg","../img/screen/a1/2.jpg","../img/screen/a1/3.jpg"],
			"brand":"Fendi 芬迪",
			"info":"貂皮 女士 挂饰",
			"price":"￥3800.00",
			"color":"#EC69AA",
			"size":["无"],
			"num":"334871",
			"goosNum":"fen0230005pin",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"粉色",
			"season":"-",
			"serise":"-",
			"mateirs":"99%貂皮",
			"desc":"颜色：粉色/蓝色",
			"story":"芬迪FENDI是意大利**的**品牌，1925年芬迪品牌正式创立于罗马，专门生产高品质毛皮制品。**的手工和工艺传统，体现芬迪奢华品质的精髓。芬迪FENDI的产品包括皮草用品，**时装，时尚包具，男女配饰及香水等。FENDI丰富的质感结合品牌文化根基，成为永恒的经典。",
			"logoBg":"../img/screen/a1/bd.jpg"
		},
		"a2":{
			"sider":["../img/screen/a2/1.jpg","../img/screen/a2/2.jpg","../img/screen/a2/3.jpg"],
			"brand":"Gucci 古驰",
			"info":"皮革 女士 钥匙扣",
			"price":"￥1950.00",
			"color":"#E53C26",
			"size":["无"],
			"num":"334916",
			"goosNum":"guc0229100blk",
			"address":"N/A",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"红色",
			"season":"-",
			"serise":"-",
			"mateirs":"皮革",
			"desc":"-",
			"story":"由Guccio Gucci创立的GUCCI王国于1921年创建于意大利的佛罗伦萨，产品涵盖服装、皮包皮鞋、手表、家饰品、宠物用品、丝巾与领带，更在1975年推出古驰香水产品。GUCCI一直以生产**豪华的产品**。无论是鞋、包还是服装，都以“身份与财富之象征”品牌形象成为富有的上流社会的消费宠儿。从40年代末到60年代，GUCCI接连推出了带竹柄的皮包、镶金属袢的软鞋、印花丝巾等一系列的经典设计，其产品的独特设计和优良材料，成为典雅和奢华的象征。",
			"logoBg":"../img/screen/a2/bd.jpg"
		},
		"a3":{
			"sider":["../img/screen/a3/1.jpg","../img/screen/a3/2.jpg","../img/screen/a3/3.jpg"],
			"brand":"ISABEL 伊珊贝",
			"info":"珍珠/18K 女士 耳饰",
			"price":"￥1680.00",
			"color":"#F2D8CE",
			"size":["无"],
			"num":"336526",
			"goosNum":"112917",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"女士",
			"color1":"多色",
			"season":"-",
			"serise":"-",
			"mateirs":"珍珠/18K",
			"desc":"此款为Isabel轻奢珍珠系列中的一款耳环，选用日本天然海珠， 直径为7.0-7.5mm ，圆形部分材质为18k玫瑰金，珍珠可以随意取下，是一款两戴款耳环。    ",
			"story":"Isabel 珠宝品牌创立于香港，珠宝主要以优雅、浪漫、灵动、为主要设计风格。分别由来自香港、意大利的珠宝手绘师设计，由台湾工匠全手工工艺打造，共同承载着珠宝的守护梦想。每一件作品的成就都从Isabel 对珠宝的精心挑选开始，打造出一个灵动浪漫的Isabel 珠宝花园。",
			"logoBg":"../img/screen/a3/bd.jpg"
		},
		"a4":{
			"sider":["../img/screen/a4/1.jpg","../img/screen/a4/2.jpg","../img/screen/a4/3.jpg"],
			"brand":"ISABEL 伊珊贝",
			"info":"珍珠/18K 女士 颈饰",
			"price":"￥1390.00",
			"color":"#B4954B",
			"size":["42"],
			"num":"336520",
			"goosNum":"112923",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"女士",
			"color1":"多色",
			"season":"-",
			"serise":"-",
			"mateirs":"珍珠/18K",
			"desc":"此款项链是ISABEL轻奢珍珠系列之一，链子部分使用18k材质，镂空正方体可以打开，里面放入的珍珠选用日本天然海水珍珠，直径为7.0-7.5mm 正圆无瑕，光泽好。简约中带有小设计，适合任何场合。",
			"story":"Isabel 珠宝品牌创立于香港，珠宝主要以优雅、浪漫、灵动、为主要设计风格。分别由来自香港、意大利的珠宝手绘师设计，由台湾工匠全手工工艺打造，共同承载着珠宝的守护梦想。每一件作品的成就都从Isabel 对珠宝的精心挑选开始，打造出一个灵动浪漫的Isabel 珠宝花园。",
			"logoBg":"../img/screen/a3/bd.jpg"
		},
		"a5":{
			"sider":["../img/screen/a5/1.jpg","../img/screen/a5/2.jpg","../img/screen/a5/3.jpg"],
			"brand":"Anya Hindmarch 安雅•希德玛芝",
			"info":"绒面皮、玻璃 女士Lips贴纸",
			"price":"￥927.00",
			"color":"#E84A35",
			"size":["无"],
			"num":"120968",
			"goosNum":"1180_259",
			"address":"-",
			"year":"-",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"红色",
			"season":"-",
			"serise":"-",
			"mateirs":"绒面皮、玻璃",
			"desc":"Anya Hindmarch 红色 绒面皮Lips贴纸。尺寸：宽度：8cm,长度：4.1cm货号：5050925931182",
			"story":"安雅•希德玛芝（Anya HindMarch）是近几年徐苏崛起的**品品牌，设计师Anya Hindmarch早已是英国公认的****的手袋设计师，并且在2006年和2007年两度获得《Glamour》杂志的年度设计师称号，在2007年又荣获British Fashion Awards颁发的年度设计师品牌头衔。",
			"logoBg":"../img/screen/a5/bd.jpg"
		},
		"a6":{
			"sider":["../img/screen/a6/1.jpg","../img/screen/a6/2.jpg","../img/screen/a6/3.jpg"],
			"brand":"Anya Hindmarch 安雅•希德玛芝",
			"info":"水晶 绒面皮 女士Lips贴纸",
			"price":"￥780.00",
			"color":"#E53F28",
			"size":["无"],
			"num":"120610",
			"goosNum":"1136_259",
			"address":"-",
			"year":"-",
			"time":"该商品到货时间预计15-20个工作日,具体时间受海关放行效率影响。",
			"fit":"女士",
			"color1":"红色",
			"season":"-",
			"serise":"-",
			"mateirs":"水晶、绒面皮",
			"desc":"Anya Hindmarch 红色与黑色 绒面皮与水晶Heart贴纸。此商是品牌与Chaos Fashion合作设计的**性贴纸。货号：5050925931090",
			"story":"安雅•希德玛芝（Anya HindMarch）是近几年徐苏崛起的**品品牌，设计师Anya Hindmarch早已是英国公认的****的手袋设计师，并且在2006年和2007年两度获得《Glamour》杂志的年度设计师称号，在2007年又荣获British Fashion Awards颁发的年度设计师品牌头衔。",
			"logoBg":"../img/screen/a5/bd.jpg"
		},
		"a7":{
			"sider":["../img/screen/a7/1.jpg","../img/screen/a7/2.jpg","../img/screen/a7/3.jpg"],
			"brand":"ISABEL 伊珊贝",
			"info":"珍珠/18K 女士 耳饰",
			"price":"￥550.00",
			"color":"#F5F5F5",
			"size":["无"],
			"num":"336529",
			"goosNum":"112914",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"女士",
			"color1":"多色",
			"season":"-",
			"serise":"-",
			"mateirs":"珍珠/18K",
			"desc":"此款珍珠选用日本天然海水珍珠，直径为3.5-4.0mm 简单的18K白金耳线凸显垂坠感，搭配珍珠的点缀，小巧精致。",
			"story":"Isabel 珠宝品牌创立于香港，珠宝主要以优雅、浪漫、灵动、为主要设计风格。分别由来自香港、意大利的珠宝手绘师设计，由台湾工匠全手工工艺打造，共同承载着珠宝的守护梦想。每一件作品的成就都从Isabel 对珠宝的精心挑选开始，打造出一个灵动浪漫的Isabel 珠宝花园。",
			"logoBg":"../img/screen/a3/bd.jpg"
		},
		"a8":{
			"sider":["../img/screen/a8/1.jpg","../img/screen/a8/2.jpg","../img/screen/a8/3.jpg","../img/screen/a8/4.jpg"],
			"brand":"Lili M",
			"info":"2017FW | Christmas Special: LA LUMIERE 水滴闪钻耳环",
			"price":"￥470.00",
			"color":"#F2F1FB",
			"size":["无"],
			"num":"336529",
			"goosNum":"112914",
			"address":"中国内地(主要地区)",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"女士",
			"color1":"金色",
			"season":"秋冬新款",
			"serise":"Christmas Special: LA LUMIERE",
			"mateirs":"14k注金、淡水珍珠",
			"desc":"14k注金微镶锆石、 淡水珍珠 *天然珍珠是每颗颜色都是独特的，有细微差别 '用附赠的擦银布轻轻擦拭就可以恢复光亮'",
			"story":'Lili M是珠宝&礼物&生活美学品的集合。将"记录每一个被宠爱的时刻”融入设计创作，传达微妙精致的轻奢珠宝搭配理念和自然放松的时髦生活方式。2012年在巴黎游学期间，创始人Lili与巴黎新晋摄影师Antoine Deroy及旅法日籍模特Yurie NK成立了独立珠宝设计工作室，并于2015年回国后创立了Lili M个人珠宝品牌，用18k金、925银、天然珍珠等材料本身所具有的质感，将其融合在不同系列的设计中，秉承**珠宝独有的镶嵌技艺，让简洁干练的金属切割与温和柔软的珍珠光泽相碰撞。法语里有一个词叫Sophistiqué，是巴黎女人**喜爱的一种复杂微妙的美感，也是Lili M一直追求的美学特色。',
			"logoBg":"../img/screen/a8/bd.jpg"
		},
		"b1":{
			"sider":["../img/screen/b1/1.jpg","../img/screen/b1/2.jpg","../img/screen/b1/3.jpg","../img/screen/b1/4.jpg"],
			"brand":"Prada 普拉达",
			"info":"尼龙布配皮 男士 平底鞋",
			"price":"￥4000.00",
			"color":"#ABABAB",
			"size":["9"],
			"num":"107683",
			"goosNum":"4T2723 3F8E F0480_165",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"灰色",
			"season":"-",
			"serise":"-",
			"mateirs":"尼龙布配皮",
			"desc":"灰色尼龙布配皮材质，系带拉链闭合，高帮鞋帮，圆头鞋头",
			"story":'意大利品牌Prada于1913年由创始人Mario Prada在米兰创建，由其所设计的时尚而品质**的手袋、旅行箱、皮质配件及化妆箱等系列产品，得到了来自皇室和上流社会的宠爱和追捧。上世纪70年代，Mario Prada的孙女Miuccia Prada接手Prada。Miuccia Prada的独特天赋在于对新创意的不懈追求,融合了对知识的好奇心和文化兴趣,从而开辟了先驱之路。她不仅能够预测时尚趋势,更能够引领时尚潮流。Prada提供男女成衣、皮具、鞋履、眼镜及香水,并提供量身定制服务。',
			"logoBg":"../img/screen/b1/bd.jpg"
		},
		"b2":{
			"sider":["../img/screen/b2/1.jpg","../img/screen/b2/2.jpg","../img/screen/b2/3.jpg","../img/screen/b2/4.jpg","../img/screen/b2/5.jpg"],
			"brand":"Prada 普拉达",
			"info":"牛皮 男士 套脚休闲皮鞋",
			"price":"￥3900.00",
			"color":"#3369EB",
			"size":["9"],
			"num":"115762",
			"goosNum":"2DE086 3Q0H F0207_165",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"蓝色",
			"season":"-",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"蓝灰色牛皮材质，套脚闭合，圆头鞋头，前襟矩形金属扣拌点缀",
			"story":'意大利品牌Prada于1913年由创始人Mario Prada在米兰创建，由其所设计的时尚而品质**的手袋、旅行箱、皮质配件及化妆箱等系列产品，得到了来自皇室和上流社会的宠爱和追捧。上世纪70年代，Mario Prada的孙女Miuccia Prada接手Prada。Miuccia Prada的独特天赋在于对新创意的不懈追求,融合了对知识的好奇心和文化兴趣,从而开辟了先驱之路。她不仅能够预测时尚趋势,更能够引领时尚潮流。Prada提供男女成衣、皮具、鞋履、眼镜及香水,并提供量身定制服务。',
			"logoBg":"../img/screen/b1/bd.jpg"
		},
		"b3":{
			"sider":["../img/screen/b3/1.jpg","../img/screen/b3/2.jpg","../img/screen/b3/3.jpg","../img/screen/b3/4.jpg","../img/screen/b3/5.jpg"],
			"brand":"Prada 普拉达",
			"info":"牛皮 女士 中跟皮鞋",
			"price":"￥5400.00",
			"color":"#2A2A2A",
			"size":["35.5","36",'36.5','37','37.5'],
			"num":"271702",
			"goosNum":"1D074H 055 F0002_165",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"黑色",
			"season":"-",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"黑色牛皮材质，套脚搭扣闭合，鞋面流苏点缀，胶质厚底，优质内村搭配立体底垫黑色牛皮前襟搭扣设计女士中跟鞋",
			"story":'意大利品牌Prada于1913年由创始人Mario Prada在米兰创建，由其所设计的时尚而品质**的手袋、旅行箱、皮质配件及化妆箱等系列产品，得到了来自皇室和上流社会的宠爱和追捧。上世纪70年代，Mario Prada的孙女Miuccia Prada接手Prada。Miuccia Prada的独特天赋在于对新创意的不懈追求,融合了对知识的好奇心和文化兴趣,从而开辟了先驱之路。她不仅能够预测时尚趋势,更能够引领时尚潮流。Prada提供男女成衣、皮具、鞋履、眼镜及香水,并提供量身定制服务。',
			"logoBg":"../img/screen/b1/bd.jpg"
		},
		"b4":{
			"sider":["../img/screen/b4/1.jpg","../img/screen/b4/2.jpg","../img/screen/b4/3.jpg","../img/screen/b4/4.jpg","../img/screen/b4/5.jpg"],
			"brand":"Gucci 古驰",
			"info":"2017年全新款式时尚女士光学镜架",
			"price":"￥1620.00",
			"color":"#2A2A2A",
			"size":["55"],
			"num":"123831",
			"goosNum":"0042OA001_150",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"黑色",
			"season":"春夏新款",
			"serise":"Christmas Special: LA LUMIERE",
			"mateirs":"板材拼接树脂",
			"desc":"镜盒 镜布 国际保证卡 产品说明书 镜面宽度55 鼻梁宽度13 镜腿长度145 单位：mm",
			"story":'由Guccio Gucci创立的GUCCI王国于1921年创建于意大利的佛罗伦萨，产品涵盖服装、皮包皮鞋、手表、家饰品、宠物用品、丝巾与领带，更在1975年推出古驰香水产品。GUCCI一直以生产**豪华的产品**。无论是鞋、包还是服装，都以“身份与财富之象征”品牌形象成为富有的上流社会的消费宠儿。从40年代末到60年代，GUCCI接连推出了带竹柄的皮包、镶金属袢的软鞋、印花丝巾等一系列的经典设计，其产品的独特设计和优良材料，成为典雅和奢华的象征',
			"logoBg":"../img/screen/a2/bd.jpg"

		},
		"b5":{
			"sider":["../img/screen/b5/1.jpg","../img/screen/b5/2.jpg","../img/screen/b5/3.jpg","../img/screen/b5/4.jpg","../img/screen/b5/5.jpg"],
			"brand":"Moncler 蒙口",
			"info":"17新款 羽绒 儿童 连帽羽绒服",
			"price":"￥3313.00",
			"color":"#2F67EA",
			"size":["10A","8A"],
			"num":"320290",
			"goosNum":"4182099 53279 758 8A-10A",
			"address":"格鲁吉亚",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"儿童",
			"color1":"蓝色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"羽绒 尼龙 羽毛",
			"desc":"-",
			"story":"Moncler是一家总部位于法国格勒诺布尔专门从事生产户外运动装备的**品牌。Moncler品牌名来自于小镇Monestier de Clermon的缩写。Moncler的故事开始于第二次世界大战期间，品牌具有传奇历史，时至今日Moncler在户外羽绒服业界中，成为首屈一指的国际品牌。80年代末，Moncler进军时尚领域，深受很多明星比如王菲，张曼玉，梁朝伟等很多香港明星的挚爱。",
			"logoBg":"../img/screen/b5/bd.jpg"
		},
		"b6":{
			"sider":["../img/screen/b6/1.jpg","../img/screen/b6/2.jpg","../img/screen/b6/3.jpg","../img/screen/b6/4.jpg","../img/screen/b6/5.jpg"],
			"brand":"Versace Collection 范思哲系列",
			"info":"羊毛混纺 男士 套装西服",
			"price":"￥6000.00",
			"color":"#A9A9A9",
			"size":["48","52"],
			"num":"84767",
			"goosNum":"V100000 VB1030",
			"address":"罗马尼亚",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"灰色",
			"season":"-",
			"serise":"-",
			"mateirs":"80%纯羊毛10%聚酰胺纤维涤纶",
			"desc":"棕灰色羊毛混纺面料，前襟纽扣闭合，平驳领领型，条纹图案，后侧开叉设计，有插袋",
			"story":"Versace Collection是全球知名**品集团Versace（范思哲）旗下**成衣品牌，品牌定位为25岁~35岁的女性。2009 年，在创意总监Donatella Versace的带领下，Versace Collection女装系列正式诞生。该品牌服装和配饰拥有毋庸置疑的品质和强烈的时尚感，相比于Versace**时装系列，Versace Collection少了几分浮夸，多了几分高雅，更适宜日常穿着。利落的剪裁雕塑出女性柔美的线条，微妙的细节处理满足了那些想要打扮得时尚而且充满个性，入时而又迷人。",
			"logoBg":"../img/screen/b6/bd.jpg"
		},
		"b7":{
			"sider":["../img/screen/b7/1.jpg","../img/screen/b7/2.jpg","../img/screen/b7/3.jpg","../img/screen/b7/4.jpg","../img/screen/b7/5.jpg"],
			"brand":"Prada 普拉达",
			"info":"【新品上市】黑色连帽拼接设计男士棉服",
			"price":"￥5700.00",
			"color":"#2A2A2A",
			"size":['M'],
			"num":"335664",
			"goosNum":"SJC332 Q86 F0002",
			"address":"罗马尼亚",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"黑色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"锦纶",
			"desc":"前幅及村里锦纶 后幅衣袖及风帽棉 填充物：聚酯纤维",
			"story":'意大利品牌Prada于1913年由创始人Mario Prada在米兰创建，由其所设计的时尚而品质**的手袋、旅行箱、皮质配件及化妆箱等系列产品，得到了来自皇室和上流社会的宠爱和追捧。上世纪70年代，Mario Prada的孙女Miuccia Prada接手Prada。Miuccia Prada的独特天赋在于对新创意的不懈追求,融合了对知识的好奇心和文化兴趣,从而开辟了先驱之路。她不仅能够预测时尚趋势,更能够引领时尚潮流。Prada提供男女成衣、皮具、鞋履、眼镜及香水,并提供量身定制服务。',
			"logoBg":"../img/screen/b1/bd.jpg"
		},
		"b8":{
			"sider":["../img/screen/b8/1.jpg","../img/screen/b8/2.jpg","../img/screen/b8/3.jpg","../img/screen/b8/4.jpg","../img/screen/b8/5.jpg"],
			"brand":"Prada 普拉达",
			"info":"桑蚕丝混纺 男士 长袖针织/毛衫",
			"price":"￥3000.00",
			"color":"#2A2A2A",
			"size":['50'],
			"num":"116808",
			"goosNum":"UMN516 648 F0002_165",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"黑色",
			"season":"-",
			"serise":"-",
			"mateirs":"桑蚕丝混纺",
			"desc":"套头闭合，V领领型，纯色图案，简约设计，黑色V领男士针织衫",
			"story":'意大利品牌Prada于1913年由创始人Mario Prada在米兰创建，由其所设计的时尚而品质**的手袋、旅行箱、皮质配件及化妆箱等系列产品，得到了来自皇室和上流社会的宠爱和追捧。上世纪70年代，Mario Prada的孙女Miuccia Prada接手Prada。Miuccia Prada的独特天赋在于对新创意的不懈追求,融合了对知识的好奇心和文化兴趣,从而开辟了先驱之路。她不仅能够预测时尚趋势,更能够引领时尚潮流。Prada提供男女成衣、皮具、鞋履、眼镜及香水,并提供量身定制服务。',
			"logoBg":"../img/screen/b1/bd.jpg"
		},
		"b9":{
			"sider":["../img/screen/b9/1.jpg","../img/screen/b9/2.jpg","../img/screen/b9/3.jpg","../img/screen/b9/4.jpg","../img/screen/b9/5.jpg"],
			"brand":"Dsquared2 D二次方",
			"info":"棉质混纺 男士 牛仔裤",
			"price":"￥2400.00",
			"color":"#3168EB",
			"size":['44',"46"],
			"num":"222832",
			"goosNum":"S74LA0705 S30342 470",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"男士",
			"color1":"蓝色",
			"season":"-",
			"serise":"-",
			"mateirs":"98%棉2%氨纶",
			"desc":"蓝色棉质混纺面料，中腰腰型，五个插袋，破洞磨白设计，前襟纽扣闭合，点缀品牌Logo标识",
			"story":'Dsquared2是由一对加拿大兄弟打造的意大利品牌。简约舒适、性感、浪漫、狂野、让人又爱又恨是这个品牌的主要风格。在意大利提到DSquared2，就是代表一种个性与时尚的撞击！品牌刚创立时就得到了时装**之一的麦当娜(Madonna)和其他明星的垂青。加拿大的智慧、意大利的精美缝制、对细节的讲究，是今天Dsquared2的哲学理念，也因此诞生了另类奢华的概念。Dsquared2的时装征服了更广泛的大众，归因于品牌风格的自然成熟，更为时髦和精致，同时保持深嵌于其设计根源的性感和挑衅的特征。',
			"logoBg":"../img/screen/b9/bd.jpg"
		},
		"b10":{
			"sider":["../img/screen/b10/1.jpg","../img/screen/b10/2.jpg","../img/screen/b10/3.jpg","../img/screen/b10/4.jpg","../img/screen/b10/5.jpg"],
			"brand":"Miu Miu 缪缪",
			"info":"【2017年新款】深蓝色羊毛女士短裤",
			"price":"￥2400.00",
			"color":"#2963E9",
			"size":['38'],
			"num":"305948",
			"goosNum":"MP1095 S31 F0008",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"蓝色",
			"season":"-",
			"serise":"-",
			"mateirs":"羊毛",
			"desc":"-",
			"story":'Miu Miu是意大利**品牌Prada的副线，Miu Miu以更年青的顾客为销售对象，风格上，比主线年青跳脱。这不但为Prada的品牌风格开辟了一片新天空。Miu Miu的由来就是Prada第三代传人Miuccia Prada小姐的昵称，风格也像小女孩一样甜美。miuccia prada似乎私心地将**正**玩**过瘾的设计都放在miu miu之上，实现了一众大女人梦想返回小女孩的现实——child women。品牌也因为如此年轻，才可让prada小姐得以尽情发挥其童心未泯的真个性。Miu Miu成为九十年代**代表性的意大利品牌之一。',
			"logoBg":"../img/screen/b10/bd.jpg"
		},
		"b11":{
			"sider":["../img/screen/b11/1.jpg","../img/screen/b11/2.jpg","../img/screen/b11/3.jpg","../img/screen/b11/4.jpg","../img/screen/b11/5.jpg"],
			"brand":"Salvatore Ferragamo 菲拉格慕",
			"info":"女士单鞋",
			"price":"￥3300.00",
			"color":"#2A2A2A",
			"size":['7','8'],
			"num":"240926",
			"goosNum":"603804RF45802",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"黑色",
			"season":"-",
			"serise":"-",
			"mateirs":"牛皮",
			"desc":"-",
			"story":'创造力、激情和韧性是Ferragamo家族恒久不变的价值观。创始人Salvatore Ferragamo先生异常关注质量和细节，他赢得了"明星御用皮鞋匠"的称号。Salvatore Ferragamo的设计风格华贵典雅，实用性和款式并重，以传统手工设计和款式，在世界各地**品界享用美誉。Salvatore Ferragamo的鞋履制作坚信--舒适与流行是不相矛盾的，这也一直是这个品牌的设计核心概念，同时兼顾健康和时髦。在每一季的新品中通常都分为经典与流行两个路线。随着时尚圈的新趋势，Ferragamo逐渐顺应潮流，品牌更呈现年轻化并受人青睐。',
			"logoBg":"../img/screen/b11/bd.jpg"
		},
		"b12":{
			"sider":["../img/screen/b12/1.jpg","../img/screen/b12/2.jpg","../img/screen/b12/3.jpg"],
			"brand":"BRAND UNIQUE",
			"info":"针织 女士 短袖针织/毛衫",
			"price":"￥1710.00",
			"color":"#9FBA55",
			"size":['38','40'],
			"num":"338868",
			"goosNum":"BUQ01W1BB03149",
			"address":"	N/A",
			"year":"2018",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"绿色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"针织",
			"desc":"-",
			"story":'BRAND UNIQUE，意大利时尚女装品牌，成立于2012年。如同品牌名所寓意的那样，BRAND UNIQUE展现的是一种诙谐有趣、young时尚风格。品牌每一季的主题创作都融合了设计师天马行空的大胆创想，创造一个又一个不可复制的时尚童话；时而浪漫摇滚、时而复古繁华、时而又清醒自然。明亮的色彩组合、精致的手工刺绣、前卫的烫金图案甚至是繁复的蕾丝工艺都展现出设计师不俗的创意才能和浪漫的表现手法。',
			"logoBg":"../img/screen/b12/bd.jpg"
		},
		"w1":{
			"sider":["../img/screen/w1/1.jpg","../img/screen/w1/2.jpg","../img/screen/w1/3.jpg","../img/screen/w1/4.jpg","../img/screen/w1/5.jpg"],
			"brand":"Gucci 古驰",
			"info":"2017年全新款式时尚女士光学镜架",
			"price":"￥1620.00",
			"color":"#2A2A2A",
			"size":["55"],
			"num":"123831",
			"goosNum":"0042OA001_150",
			"address":"意大利",
			"year":"-",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"黑色",
			"season":"春夏新款",
			"serise":"Christmas Special: LA LUMIERE",
			"mateirs":"板材拼接树脂",
			"desc":"镜盒 镜布 国际保证卡 产品说明书 镜面宽度55 鼻梁宽度13 镜腿长度145 单位：mm",
			"story":'由Guccio Gucci创立的GUCCI王国于1921年创建于意大利的佛罗伦萨，产品涵盖服装、皮包皮鞋、手表、家饰品、宠物用品、丝巾与领带，更在1975年推出古驰香水产品。GUCCI一直以生产**豪华的产品**。无论是鞋、包还是服装，都以“身份与财富之象征”品牌形象成为富有的上流社会的消费宠儿。从40年代末到60年代，GUCCI接连推出了带竹柄的皮包、镶金属袢的软鞋、印花丝巾等一系列的经典设计，其产品的独特设计和优良材料，成为典雅和奢华的象征',
			"logoBg":"../img/screen/a2/bd.jpg"
		},
		"w2":{
			"sider":["../img/screen/w2/1.jpg","../img/screen/w2/2.jpg","../img/screen/w2/3.jpg","../img/screen/w2/4.jpg"],
			"brand":"Saint Laurent 圣罗兰",
			"info":"皮革 女士 长钱包",
			"price":"￥1440.00",
			"color":"#2E66EA",
			"size":["无"],
			"num":"339035",
			"goosNum":"sla0230033blu",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
			"fit":"女士",
			"color1":"蓝色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"99%皮革",
			"desc":"-",
			"story":'上世纪60年代，执时装界牛耳的Yves Saint Laurent先生，用巴黎左岸创新、时尚的风情，开创了色彩缤纷、浪漫高雅的Yves Saint Laurent 时代。他**地改变了女性的着装规则——他创举性地引进了曾是男士专属的西裤套装、狩猎外套和燕尾服到女装领域。YSL女装的常见款式，像吸烟装、吸烟裤，厚质面料的挺括与造型设计的雅致恰好相得益彰。品牌的旗舰产品至今仍然是昂贵的**时装，产品中包括时装，香水、饰品、鞋帽,、护肤化妆品及香烟等。',
			"logoBg":"../img/screen/w2/bd.jpg"
		},
		"w3":{
			"sider":["../img/screen/w3/1.jpg","../img/screen/w3/2.jpg","../img/screen/w3/3.jpg","../img/screen/w3/4.jpg"],
			"brand":"ELITESIGNER x SIA KARATI",
			"info":"9K黄金精华素耳扣",
			"price":"￥860.00",
			"color":"#CCB98E",
			"size":["50"],
			"num":"338965",
			"goosNum":"ESSK01",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"金色",
			"season":"-",
			"serise":"ESSENCE精华素系列",
			"mateirs":"9K黄金",
			"desc":"Sia Karati的经典元素“药丸”在新的系列中得到延续，新系列设计中更增添了一份沉稳优雅。ESSENCE精华素系列以9k金打造，简约中又透露着有趣的线条感，小小点缀却魅力十足。",
			"story":'ELITESIGNER星设汇是汇聚新晋珠宝设计师的时尚聚集地。致力推荐优质的珠宝设计师和他们的独立品牌，给以独特、新颖、原创的珠宝及定制体验，提供潮流设计，享受设计定制。ES旗下合作设计师品牌SIA KARATI由留意设计师Sia Deng创立。意大利语里sia是essere的虚拟语气变形，虚拟语气代表说的东西不是事实，只是假设想象或愿望。Karati是珠宝单位Carati的改写，即是克拉也非克拉。Sia Karati就是设计师Sia Deng对首饰和配饰的一种想象，猜测怀疑原本的定义，通过配首饰和配饰作为载体，解读和表达个人的愿望和情感，将思绪和信仰全部赋予其中。如同书里的文字，肌肤上的纹身，SiaDeng希望用首饰固态的形式将无形的回忆或意识存放，让每克拉里的首饰都变成佩带者的一种精神和灵魂的记录者。',
			"logoBg":"../img/screen/w3/bd.jpg"
		},
		"w4":{
			"sider":["../img/screen/w4/1.jpg","../img/screen/w4/2.jpg","../img/screen/w4/3.jpg","../img/screen/w4/4.jpg","../img/screen/w4/5.jpg"],
			"brand":"ELITESIGNER x SIA KARATI",
			"info":"9K黄金珍珠精华素耳环",
			"price":"￥880.00",
			"color":"#CCB98E",
			"size":["50"],
			"num":"338964",
			"goosNum":"ESSD017",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"金色",
			"season":"-",
			"serise":"ESSENCE精华素系列",
			"mateirs":"9K黄金/珍珠",
			"desc":"Sia Karati的经典元素“药丸”在新的系列中得到延续，新系列设计中更增添了一份沉稳优雅。ESSENCE精华素系列以9k金打造，简约中又透露着有趣的线条感，小小点缀却魅力十足。",
			"story":'ELITESIGNER星设汇是汇聚新晋珠宝设计师的时尚聚集地。致力推荐优质的珠宝设计师和他们的独立品牌，给以独特、新颖、原创的珠宝及定制体验，提供潮流设计，享受设计定制。ES旗下合作设计师品牌SIA KARATI由留意设计师Sia Deng创立。意大利语里sia是essere的虚拟语气变形，虚拟语气代表说的东西不是事实，只是假设想象或愿望。Karati是珠宝单位Carati的改写，即是克拉也非克拉。Sia Karati就是设计师Sia Deng对首饰和配饰的一种想象，猜测怀疑原本的定义，通过配首饰和配饰作为载体，解读和表达个人的愿望和情感，将思绪和信仰全部赋予其中。如同书里的文字，肌肤上的纹身，SiaDeng希望用首饰固态的形式将无形的回忆或意识存放，让每克拉里的首饰都变成佩带者的一种精神和灵魂的记录者。',
			"logoBg":"../img/screen/w3/bd.jpg"
		},
	"w5":{
			"sider":["../img/screen/w5/1.jpg","../img/screen/w5/2.jpg","../img/screen/w5/3.jpg","../img/screen/w5/4.jpg","../img/screen/w5/5.jpg",],
			"brand":"ELITESIGNER x SIA KARATI",
			"info":"14K黄金精华素双链吊坠",
			"price":"￥3600.00",
			"color":"#CCB98E",
			"size":["50"],
			"num":"338962",
			"goosNum":"ESSD018",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"金色",
			"season":"-",
			"serise":"ESSENCE精华素系列",
			"mateirs":"14K黄金",
			"desc":"Sia Karati的经典元素“药丸”在新的系列中得到延续，新系列设计中更增添了一份沉稳优雅。ESSENCE精华素系列以9k金打造，简约中又透露着有趣的线条感，小小点缀却魅力十足。",
			"story":'ELITESIGNER星设汇是汇聚新晋珠宝设计师的时尚聚集地。致力推荐优质的珠宝设计师和他们的独立品牌，给以独特、新颖、原创的珠宝及定制体验，提供潮流设计，享受设计定制。ES旗下合作设计师品牌SIA KARATI由留意设计师Sia Deng创立。意大利语里sia是essere的虚拟语气变形，虚拟语气代表说的东西不是事实，只是假设想象或愿望。Karati是珠宝单位Carati的改写，即是克拉也非克拉。Sia Karati就是设计师Sia Deng对首饰和配饰的一种想象，猜测怀疑原本的定义，通过配首饰和配饰作为载体，解读和表达个人的愿望和情感，将思绪和信仰全部赋予其中。如同书里的文字，肌肤上的纹身，SiaDeng希望用首饰固态的形式将无形的回忆或意识存放，让每克拉里的首饰都变成佩带者的一种精神和灵魂的记录者。',
			"logoBg":"../img/screen/w3/bd.jpg"
		},
	"w6":{
			"sider":["../img/screen/w6/1.jpg","../img/screen/w6/2.jpg","../img/screen/w6/3.jpg","../img/screen/w6/4.jpg"],
			"brand":"ELITESIGNER x SIA KARATI",
			"info":"9K黄金精华素耳钉",
			"price":"￥1750.00",
			"color":"#CCB98E",
			"size":["50"],
			"num":"338962",
			"goosNum":"ESSD019",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"金色",
			"season":"-",
			"serise":"ESSENCE精华素系列",
			"mateirs":"9K黄金",
			"desc":"Sia Karati的经典元素“药丸”在新的系列中得到延续，新系列设计中更增添了一份沉稳优雅。ESSENCE精华素系列以9k金打造，简约中又透露着有趣的线条感，小小点缀却魅力十足。",
			"story":'ELITESIGNER星设汇是汇聚新晋珠宝设计师的时尚聚集地。致力推荐优质的珠宝设计师和他们的独立品牌，给以独特、新颖、原创的珠宝及定制体验，提供潮流设计，享受设计定制。ES旗下合作设计师品牌SIA KARATI由留意设计师Sia Deng创立。意大利语里sia是essere的虚拟语气变形，虚拟语气代表说的东西不是事实，只是假设想象或愿望。Karati是珠宝单位Carati的改写，即是克拉也非克拉。Sia Karati就是设计师Sia Deng对首饰和配饰的一种想象，猜测怀疑原本的定义，通过配首饰和配饰作为载体，解读和表达个人的愿望和情感，将思绪和信仰全部赋予其中。如同书里的文字，肌肤上的纹身，SiaDeng希望用首饰固态的形式将无形的回忆或意识存放，让每克拉里的首饰都变成佩带者的一种精神和灵魂的记录者。',
			"logoBg":"../img/screen/w3/bd.jpg"
		},
	"w7":{
			"sider":["../img/screen/w7/1.jpg","../img/screen/w7/2.jpg","../img/screen/w7/3.jpg","../img/screen/w7/4.jpg","../img/screen/w7/5.jpg"],
			"brand":"Fondamentale",
			"info":"羊绒99% 女士 围巾",
			"price":"￥690.00",
			"color":"#2B64E9",
			"size":["无"],
			"num":"339015",
			"goosNum":"F17CJ004",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"蓝色",
			"season":"春夏新款",
			"serise":"-",
			"mateirs":"羊绒99%",
			"desc":"Fondamentale 羊绒超薄色织条纹拼接款女士披肩 颜色：蓝色拼米白色；尺寸：200*95cm 200支精纺超细99%羊绒纱线，柔软亲肤，轻薄舒适；流行的拼色元素，两端精细短流苏设计，柔软顺滑，时尚舒适",
			"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
			"logoBg":"../img/screen/w7/bd.jpg"
		},
	"w8":{
			"sider":["../img/screen/w8/1.jpg","../img/screen/w8/2.jpg","../img/screen/w8/3.jpg","../img/screen/w8/4.jpg"],
			"brand":"Fondamentale",
			"info":"羊绒99% 女士 围巾",
			"price":"￥690.00",
			"color":"#F8F1E4",
			"size":["无"],
			"num":"339014",
			"goosNum":"F17CJ003",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"米色",
			"season":"春夏新款",
			"serise":"-",
			"mateirs":"羊绒99%",
			"desc":"Fondamentale羊绒超薄色织渐变条纹女士披肩颜色：湛蓝色条纹、樱草绿色条纹、米驼色条纹；尺寸：200*90cm 200支精纺超细99%羊绒纱线，柔软亲肤，轻薄舒适；渐变撞色条纹，更衬白皙靓丽肌肤；两端精细短流苏设计，柔软顺滑，时尚舒适",
			"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
			"logoBg":"../img/screen/w7/bd.jpg"
		},
	"w9":{
			"sider":["../img/screen/w9/1.jpg","../img/screen/w9/2.jpg","../img/screen/w9/3.jpg","../img/screen/w9/4.jpg","../img/screen/w9/5.jpg"],
			"brand":"Fondamentale",
			"info":"羊毛99%+羊皮流苏 女士 围巾",
			"price":"￥900.00",
			"color":"#985C38",
			"size":["无"],
			"num":"339013",
			"goosNum":"F17WC021",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"棕色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"羊毛99%+羊皮流苏",
			"desc":"Fondamentale 手工小羊皮流苏羔羊毛披肩颜色：气质驼；尺寸：200*65cm 1.优选初生羊毛，精工织造，软弹丰厚，配色经典，凸显气质。2.手工铆孔，甄选小羊皮，纯手工剪裁编制双层流苏。匠人态度，手工魅力。 3.来自流苏的飞扬，减轻秋冬的厚重，重塑轻灵的质感。",
			"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
			"logoBg":"../img/screen/w7/bd.jpg"
		},
	"w10":{
			"sider":["../img/screen/w10/1.jpg","../img/screen/w10/2.jpg","../img/screen/w10/3.jpg","../img/screen/w10/4.jpg","../img/screen/w10/5.jpg"],
			"brand":"Fondamentale",
			"info":"羊绒99% 女士 围巾",
			"price":"￥790.00",
			"color":"#FFE03E",
			"size":["无"],
			"num":"339012",
			"goosNum":"F17CJ006",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"黄色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"羊绒99%",
			"desc":"Fondamentale细腻轻薄羊绒粗纺围巾颜色：金菊黄、石榴红、怀旧灰、月晕蓝；尺寸：200*65cm精纺羊绒轻盈飘逸，光洁紧密，色泽纯正自然，层次丰富；特殊的粗纺工艺，细密绒面，温暖丰满，悬垂软糯，富有弹性。3.来自流苏的飞扬，减轻秋冬的厚重，重塑轻灵的质感。",
			"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
			"logoBg":"../img/screen/w10/b7.jpg"
		},
	"w11":{
			"sider":["../img/screen/w11/1.jpg","../img/screen/w11/2.jpg","../img/screen/w11/3.jpg","../img/screen/w11/4.jpg"],
			"brand":"Fondamentale",
			"info":"羊毛99% 女士 围巾",
			"price":"￥360.00",
			"color":"#453146",
			"size":["无"],
			"num":"338874",
			"goosNum":"F17WJ013",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计5-10个工作日",
			"fit":"女士",
			"color1":"紫色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"羊毛99%",
			"desc":"Fondamentale 立体方格加厚澳洲丝光羊毛披肩颜色：紫藤，尺寸：200*75cm层层筛选初生小羊羔毛，更好的还原优质羊毛的丰厚质感；精细方格立体织造，凹凸肌理质感十足，使围巾呈现出自然独特的立体廓形和肌理风格；加大加厚，保暖舒适",
			"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
			"logoBg":"../img/screen/w7/bd.jpg"
		},
	"w12":{
		"sider":["../img/screen/w12/1.jpg","../img/screen/w12/2.jpg","../img/screen/w12/3.jpg","../img/screen/w12/4.jpg"],
		"brand":"Fondamentale",
		"info":"羊毛99% 女士 围巾",
		"price":"￥360.00",
		"color":"#2F221B",
		"size":["无"],
		"num":"338873",
		"goosNum":"F17WJ013",
		"address":"中国",
		"year":"2017",
		"time":"该商品到货时间预计5-10个工作日",
		"fit":"女士",
		"color1":"黄色",
		"season":"秋冬新款",
		"serise":"-",
		"mateirs":"羊毛99%",
		"desc":"Fondamentale 时尚拼色纱羊毛围巾 颜色：夜紫、秋黄、墨绿，尺寸：220*75cm欧式设计风格，双色纱线交错混织，气质独特，突出休闲混搭风格；优选纯羊毛加厚织造，温暖你的冬日；三色可选。",
		"story":'Fondamentale，寓意为本源，由一群充满探索精神的设计师与艺术家组成。Fondamentale的饰品带着对现今时尚符号的质疑与思考，不再满足于服饰产品的实用性，装饰性及形式上的各种花巧变化，更不把获得名利作为支撑工作的目的，着力于探究内心世界深处的交流与考量。Fondamentale产品怀着对自然的敬畏和对世界初始的认识，通过质朴的、手造之物，希望治愈人们被现代时尚工业过分刺激的感官，恢复对些微末节的美的敏感，让真正的时尚回归平凡，再现非凡。Fondamentale产品的魅力，也正是打破了时尚的传统概念，把优质的质料和随意自然的本真气质结合在一起，尽可能展现织物本身的生动与丰富。看似不经意之处，却透着不凡的设计感和品牌的独特美学。Fondamentale笃信真正的奢华不由价格体现， 而在于其代表的精神。时尚稍纵即逝，精神永恒留存。',
		"logoBg":"../img/screen/w7/bd.jpg"
	},
		"f1":{
			"sider":["../img/screen/f1/1.jpg","../img/screen/f1/2.jpg","../img/screen/f1/3.jpg","../img/screen/f1/4.jpg","../img/screen/f1/5.jpg"],
			"brand":"Sretsis",
			"info":"Sretsis 针织飞马高领毛衣",
			"price":"￥2600.00",
			"color":"#994C23",
			"size":['2','4','6','8'],
			"num":"338866",
			"goosNum":"AW996",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"棕色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'Sretsis是泰国的服装品牌，它由三个极具天分的姊妹（PIM，KLY和Martina）于2002年所创立的品牌，sisters（姊妹）倒过来拼就是这个品牌名字的由来。 Sretsis品牌创立于2002年，Pim Sukhahuta200年毕业于纽约**的帕森斯设计学院，此前曾在Marc Jacobs实习。她们的设计很女性化、很温柔、很甜美又很可爱。 Sretsis进入美国时装市场的**次全新突破，目前Sretsis已被全球公认的，经常会在VOGUE，ELLE，Instyle和“纽约邮报”提名。',
			"logoBg":"../img/screen/f1/bd.jpg"
		},
		"f2":{
			"sider":["../img/screen/f2/1.jpg"],
			"brand":"Sretsis",
			"info":"Sretsis 针织飞马高领毛衣",
			"price":"￥2600.00",
			"color":"#994C23",
			"size":['2','4','6','8'],
			"num":"338871",
			"goosNum":"AW996",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"灰色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'Sretsis是泰国的服装品牌，它由三个极具天分的姊妹（PIM，KLY和Martina）于2002年所创立的品牌，sisters（姊妹）倒过来拼就是这个品牌名字的由来。 Sretsis品牌创立于2002年，Pim Sukhahuta200年毕业于纽约**的帕森斯设计学院，此前曾在Marc Jacobs实习。她们的设计很女性化、很温柔、很甜美又很可爱。 Sretsis进入美国时装市场的**次全新突破，目前Sretsis已被全球公认的，经常会在VOGUE，ELLE，Instyle和“纽约邮报”提名。',
			"logoBg":"../img/screen/f1/bd.jpg"
		},
		"f3":{
			"sider":["../img/screen/f3/1.jpg","../img/screen/f3/2.jpg","../img/screen/f3/3.jpg","../img/screen/f3/4.jpg"],
			"brand":"Sretsis",
			"info":"Sretsis ",
			"price":"￥1990.00",
			"color":"#2A2A2A",
			"size":['F'],
			"num":"334077",
			"goosNum":"SR2135",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"黑色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'Sretsis是泰国的服装品牌，它由三个极具天分的姊妹（PIM，KLY和Martina）于2002年所创立的品牌，sisters（姊妹）倒过来拼就是这个品牌名字的由来。 Sretsis品牌创立于2002年，Pim Sukhahuta200年毕业于纽约**的帕森斯设计学院，此前曾在Marc Jacobs实习。她们的设计很女性化、很温柔、很甜美又很可爱。 Sretsis进入美国时装市场的**次全新突破，目前Sretsis已被全球公认的，经常会在VOGUE，ELLE，Instyle和“纽约邮报”提名。',
			"logoBg":"../img/screen/f1/bd.jpg"
		},
		"f4":{
			"sider":["../img/screen/f4/1.jpg","../img/screen/f4/2.jpg","../img/screen/f4/3.jpg"],
			"brand":"THEA by Thara",
			"info":"长袖单扣西装外套 ",
			"price":"￥2650.00",
			"color":"#F9F9F9",
			"size":['2','4','6'],
			"num":"	334098",
			"goosNum":"	JK001WHFA17",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"白色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'THEA by Thara创造了缪斯的**线条：一个女性人物，低调的感性，体现了坚定不移的信心和独特的风格。当别致的时尚风格与亚洲文化更温和的本质融合在一起时，就被重新诠释了。THEA by Thara融合了艺术与时尚，流动性、浪漫、怀旧与建筑、凉爽和男孩气质。所有这些元素，成为了它复杂时尚创造的根源，而当想到THEA by Thara时，却会想到“细节的简单线条”。',
			"logoBg":"../img/screen/f4/bd.jpg"
		},
		"f5":{
			"sider":["../img/screen/f5/1.jpg","../img/screen/f5/2.jpg"],
			"brand":"POEM",
			"info":"POEM 软鱼骨一字领上衣 ",
			"price":"￥1900.00",
			"color":"#386167",
			"size":['32','36'],
			"num":"330409",
			"goosNum":"		1097",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"绿色",
			"season":"	春夏新款",
			"serise":"	SS17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'品牌创始人Chavanon Caisiri是建筑学研究生出身，从小在妈妈的裁缝工作室里长大。Poem品牌成立于2006年，Chavanon将法式优雅与自己所学的建筑几何学和面料的知识相结合，致力于打造一个现代的、实用的衣橱。POEM**融合了品牌创始人Chavanon Caisiri对于建筑几何学和服装的理解，精于重塑20世纪50年代贵妇淑女的形象，凭借上乘的布料材质以及无可挑剔的裁剪工艺赢得追捧。目前在泰国的各种名流聚会或活动中都有穿着poem优雅身影。',
			"logoBg":"../img/screen/f5/bd.png"
		},
		"f6":{
			"sider":["../img/screen/f6/1.jpg","../img/screen/f6/2.jpg","../img/screen/f6/3.jpg","../img/screen/f6/4.jpg","../img/screen/f6/5.jpg"],
			"brand":"THEA by Thara",
			"info":"花朵拼接丝绒连衣裙 ",
			"price":"￥2500.00",
			"color":"#E7442D",
			"size":['2','4','6'],
			"num":"		334107",
			"goosNum":"	DR002REFA17",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"红色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"	丝绒",
			"desc":"-",
			"story":'THEA by Thara创造了缪斯的**线条：一个女性人物，低调的感性，体现了坚定不移的信心和独特的风格。当别致的时尚风格与亚洲文化更温和的本质融合在一起时，就被重新诠释了。THEA by Thara融合了艺术与时尚，流动性、浪漫、怀旧与建筑、凉爽和男孩气质。所有这些元素，成为了它复杂时尚创造的根源，而当想到THEA by Thara时，却会想到“细节的简单线条”。',
			"logoBg":"../img/screen/f4/bd.jpg"
		},
		"f7":{
			"sider":["../img/screen/f7/1.jpg","../img/screen/f7/2.jpg","../img/screen/f7/3.jpg","../img/screen/f7/4.jpg","../img/screen/f7/5.jpg"],
			"brand":"Sretsis",
			"info":"Sretsis 星空主题 超长连衣裙",
			"price":"￥5940.00",
			"color":"#EAD3B9",
			"size":['2','4','6'],
			"num":"331876",
			"goosNum":"AW006",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"米色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'Sretsis是泰国的服装品牌，它由三个极具天分的姊妹（PIM，KLY和Martina）于2002年所创立的品牌，sisters（姊妹）倒过来拼就是这个品牌名字的由来。 Sretsis品牌创立于2002年，Pim Sukhahuta200年毕业于纽约**的帕森斯设计学院，此前曾在Marc Jacobs实习。她们的设计很女性化、很温柔、很甜美又很可爱。 Sretsis进入美国时装市场的**次全新突破，目前Sretsis已被全球公认的，经常会在VOGUE，ELLE，Instyle和“纽约邮报”提名。',
			"logoBg":"../img/screen/f1/bd.jpg"
		},
		"f8":{
			"sider":["../img/screen/f8/1.jpg","../img/screen/f8/2.jpg","../img/screen/f8/3.jpg","../img/screen/f8/4.jpg","../img/screen/f8/5.jpg"],
			"brand":"Sretsis",
			"info":"Sretsis 星空主题 超长连衣裙",
			"price":"￥4060.00",
			"color":"#EAD3B9",
			"size":['2','4','6'],
			"num":"331881",
			"goosNum":"SRAW05",
			"address":"	泰国",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日",
			"fit":"女士",
			"color1":"米色",
			"season":"秋冬新款",
			"serise":"AW17",
			"mateirs":"纤维",
			"desc":"-",
			"story":'Sretsis是泰国的服装品牌，它由三个极具天分的姊妹（PIM，KLY和Martina）于2002年所创立的品牌，sisters（姊妹）倒过来拼就是这个品牌名字的由来。 Sretsis品牌创立于2002年，Pim Sukhahuta200年毕业于纽约**的帕森斯设计学院，此前曾在Marc Jacobs实习。她们的设计很女性化、很温柔、很甜美又很可爱。 Sretsis进入美国时装市场的**次全新突破，目前Sretsis已被全球公认的，经常会在VOGUE，ELLE，Instyle和“纽约邮报”提名。',
			"logoBg":"../img/screen/f1/bd.jpg"
		},

		// S系列

		"s1":{
			"sider":["../img/screen/s1/1.jpg","../img/screen/s1/2.jpg","../img/screen/s1/3.jpg","../img/screen/s1/4.jpg","../img/screen/s1/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【卡趣 丫布兔】 儿童豆袋沙发",
			"price":"￥300.00",
			"color":"#EE70AF",
			"size":['无'],
			"num":"337962",
			"goosNum":"豆袋 兔子 S 粉拼",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"儿童",
			"color1":"蓝色",
			"season":"-",
			"serise":"卡趣系列",
			"mateirs":"全棉帆布",
			"desc":"-",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s2":{
			"sider":["../img/screen/s2/1.jpg","../img/screen/s2/2.jpg","../img/screen/s2/3.jpg","../img/screen/s2/4.jpg","../img/screen/s2/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【卡趣 丫布兔】 儿童豆袋沙发",
			"price":"￥300.00",
			"color":"#C6DAE9",
			"size":['无'],
			"num":"337963",
			"goosNum":"豆袋 兔子 S 蓝拼",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"儿童",
			"color1":"粉色",
			"season":"-",
			"serise":"卡趣系列",
			"mateirs":"全棉帆布",
			"desc":"-",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s3":{
			"sider":["../img/screen/s3/1.jpg","../img/screen/s3/2.jpg","../img/screen/s3/3.jpg","../img/screen/s3/4.jpg","../img/screen/s3/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【喵呜】 布艺搁脚凳坐凳",
			"price":"￥200.00",
			"color":"#F6C671",
			"size":['无'],
			"num":"337961",
			"goosNum":"脚凳 喵呜 白杨金",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"金色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"涤棉牛仔帆布",
			"desc":"1.小猫耳朵造型，自然俏皮。 2.加厚面料，牢度加强。 3.高回弹环保EPP粒子填充，比PP棉支撑更强，比木凳更轻巧 4.独立内胆，外套拆洗更省心 5.两重止口缝线，上万次耐拉牢度测试 6.可搁脚，可当坐凳，随意挪动不占地，实用性强",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s4":{
			"sider":["../img/screen/s4/1.jpg","../img/screen/s4/2.jpg","../img/screen/s4/3.jpg","../img/screen/s4/4.jpg","../img/screen/s4/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【摩登 丫布兔】成人豆袋沙发",
			"price":"￥800.00",
			"color":"#EC69AA",
			"size":['无'],
			"num":"	337960",
			"goosNum":"豆袋 兔子 L 粉拼",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"粉色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"全棉帆布",
			"desc":"-",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s5":{
			"sider":["../img/screen/s5/1.jpg","../img/screen/s5/2.jpg","../img/screen/s5/3.jpg","../img/screen/s5/4.jpg","../img/screen/s5/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【喵呜】 布艺搁脚凳坐凳",
			"price":"￥200.00",
			"color":"#63686E",
			"size":['无'],
			"num":"337959",
			"goosNum":"	脚凳 喵呜 霜冻灰",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"灰色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"涤棉牛仔帆布",
			"desc":"1.小猫耳朵造型，自然俏皮。 2.加厚面料，牢度加强。 3.高回弹环保EPP粒子填充，比PP棉支撑更强，比木凳更轻巧 4.独立内胆，外套拆洗更省心 5.两重止口缝线，上万次耐拉牢度测试 6.可搁脚，可当坐凳，随意挪动不占地，实用性强",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s6":{
			"sider":["../img/screen/s6/1.jpg","../img/screen/s6/2.jpg","../img/screen/s6/3.jpg","../img/screen/s6/4.jpg","../img/screen/s6/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【摩登 丫布兔】成人豆袋沙发",
			"price":"￥800.00",
			"color":"#DED8E4",
			"size":['无'],
			"num":"	337958",
			"goosNum":"豆袋 兔子 L 灰拼",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"灰色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"全棉帆布",
			"desc":"-",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s7":{
			"sider":["../img/screen/s7/1.jpg","../img/screen/s7/2.jpg","../img/screen/s7/3.jpg","../img/screen/s7/4.jpg","../img/screen/s7/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【喵呜】 布艺搁脚凳坐凳",
			"price":"￥200.00",
			"color":"#272E46",
			"size":['无'],
			"num":"337957",
			"goosNum":"	脚凳 喵呜 峡湾蓝",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"灰色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"涤棉牛仔帆布",
			"desc":"1.小猫耳朵造型，自然俏皮。 2.加厚面料，牢度加强。 3.高回弹环保EPP粒子填充，比PP棉支撑更强，比木凳更轻巧 4.独立内胆，外套拆洗更省心 5.两重止口缝线，上万次耐拉牢度测试 6.可搁脚，可当坐凳，随意挪动不占地，实用性强",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},
		"s8":{
			"sider":["../img/screen/s8/1.jpg","../img/screen/s8/2.jpg","../img/screen/s8/3.jpg","../img/screen/s8/4.jpg","../img/screen/s8/5.jpg"],
			"brand":"Yuppie Life 雅痞",
			"info":"【摩登 丫布兔】成人豆袋沙发",
			"price":"￥650.00",
			"color":"#7E7C7E",
			"size":['无'],
			"num":"	337956",
			"goosNum":"豆袋 兔子 L 绅士灰",
			"address":"	中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男女",
			"color1":"灰色",
			"season":"-",
			"serise":"摩登系列",
			"mateirs":"帆布",
			"desc":"-",
			"story":'“Yuppie Life”品牌创立于 2014年10月，品牌灵感来源于Hippie,Yuppie这两个单词。**终情定雅痞Yuppie，是因为它有优雅，但又有那么点坏坏的痞，就像我们希望我们的产品和服务，永远不循规蹈矩，永远带给你惊喜。 2017年，品牌正式从雅痞Yuppie升级为Yuppie Life，是我们希望，雅痞精神，能融入你生活的方方面面，融入我们和我们客户的骨子里~',
			"logoBg":"../img/screen/s1/bd.jpg"
		},

		// 男士系列
		"m1":{
			"sider":["../img/screen/m1/1.jpg","../img/screen/m1/2.jpg","../img/screen/m1/3.jpg","../img/screen/m1/4.jpg"],
			"brand":"Sunnei",
			"info":"美利奴羊毛 男士 围巾",
			"price":"￥1910.00",
			"color":"#393641",
			"size":["无"],
			"num":"339116",
			"goosNum":"sun0130014nav",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
			"fit":"男士",
			"color1":"蓝色",
			"season":"秋冬新款",
			"serise":"-",
			"mateirs":"99%美利奴羊毛",
			"desc":"颜色：海军蓝",
			"story":'Sunnei是Simone Rizz和 Loris Messino的“杰作”，两位创始人一位曾是负责采购的买手，一位是 Gucci 橱窗设计师，他们于2014年在米兰创办了男装品牌 Sunnei。品牌定位轻奢，意大利男装的悠久历史和品质保障不仅没有成为品牌发展的障碍，反而成为了其独特品质的背书，据悉品牌大部分利润来源于他们的线上渠道，但去年在米兰开出了品牌**实体旗舰店。',
			"logoBg":"../img/screen/m1/bd.jpg"
		},

		"m2":{
				"sider":["../img/screen/m2/1.jpg","../img/screen/m2/2.jpg","../img/screen/m2/3.jpg","../img/screen/m2/4.jpg"],
				"brand":"Raf Simons",
				"info":"棉质 男士 棒球帽",
				"price":"￥1380.00",
				"color":"#9D754B",
				"size":["无"],
				"num":"339074",
				"goosNum":"raf0130027brm",
				"address":"意大利",
				"year":"2017",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"棕色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"99%棉质",
				"desc":"只能干洗",
				"story":'顶风取代 John Galliano 出任 Dior 主设计师的 Raf Simons 自己的品牌包括 Raf Simons 和副线 Raf by Raf Simons，他亦曾是Jil Sander的首席设计师。RafSimons**初学习工业设计，通过自学接触服装设计。1995年， Raf Simons 创建了自己的品牌，受工业设计学习经历的影响，充满了鲜明的建构感和极简主义风格，他**擅长的就是利落的单线条的运用。他的男装设计以前卫、“革命性”著称。纽约时报曾评价他为“几乎是上世纪**影响力的男装设计师”。2012年2月25日，米兰2012秋冬时装周 Raf Simons **一次作为Jil Sander首席设计师登台谢幕。2012年4月，LVMH 集团公布消息，Raf Simons 将接替 Bill Gaytten 执掌Dior，并于巴黎时间4月9日宣布 Raf Simons 取代 John Galliano 出任 Dior 总设计师',
				"logoBg":"../img/screen/m2/bd.jpg"
			},
		"m3":{
				"sider":["../img/screen/m3/1.jpg","../img/screen/m3/2.jpg","../img/screen/m3/3.jpg","../img/screen/m3/4.jpg"],
				"brand":"Sunnei",
				"info":"美利奴羊毛 男士 围巾",
				"price":"￥1910.00",
				"color":"#3369EB",
				"size":["无"],
				"num":"339037",
				"goosNum":"sun0130010blk",
				"address":"意大利",
				"year":"2017",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"蓝色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"99%美利奴羊毛",
				"desc":"颜色：白色/海军蓝只能干洗",
				"story":'Sunnei是Simone Rizz和 Loris Messino的“杰作”，两位创始人一位曾是负责采购的买手，一位是 Gucci 橱窗设计师，他们于2014年在米兰创办了男装品牌 Sunnei。品牌定位轻奢，意大利男装的悠久历史和品质保障不仅没有成为品牌发展的障碍，反而成为了其独特品质的背书，据悉品牌大部分利润来源于他们的线上渠道，但去年在米兰开出了品牌**实体旗舰店。',
				"logoBg":"../img/screen/m1/bd.jpg"
			},
		"m4":{
				"sider":["../img/screen/m4/1.jpg","../img/screen/m4/2.jpg","../img/screen/m4/3.jpg","../img/screen/m4/4.jpg","../img/screen/m4/5.jpg"],
				"brand":"Versace Collection 范思哲系列",
				"info":"皮质 男仕 腰带",
				"price":"￥1380.00",
				"color":"#2C2F3A",
				"size":["100","105","90","95"],
				"num":"264862",
				"goosNum":"V910226 VM00043 V346V_245 ",
				"address":"-",
				"year":"-",
				"time":"该商品到货时间预计5-10个工作日",
				"fit":"男士",
				"color1":"蓝色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"**皮",
				"desc":"藏蓝色皮质材质，方形美杜莎银色金属扣",
				"story":'VersaceCollection是全球知名**品集团Versace（范思哲）旗下**成衣品牌，品牌定位为25岁~35岁的女性。2009 年，在创意总监Donatella Versace的带领下，Versace Collection女装系列正式诞生。该品牌服装和配饰拥有毋庸置疑的品质和强烈的时尚感，相比于Versace**时装系列，Versace Collection少了几分浮夸，多了几分高雅，更适宜日常穿着。利落的剪裁雕塑出女性柔美的线条，微妙的细节处理满足了那些想要打扮得时尚而且充满个性，入时而又迷人。',
				"logoBg":"../img/screen/b6/bd.jpg"
			},
			"m5":{
				"sider":["../img/screen/m5/1.jpg","../img/screen/m5/2.jpg","../img/screen/m5/3.jpg","../img/screen/m5/4.jpg","../img/screen/m5/5.jpg"],
				"brand":"VERSACE JEANS 范思哲牛仔",
				"info":"皮质 男仕 腰带",
				"price":"￥1120.00",
				"color":"#3A3A3B",
				"size":["100","105","90","95"],
				"num":"264862",
				"goosNum":"V910226 VM00043 V346V_245 ",
				"address":"-",
				"year":"-",
				"time":"该商品到货时间预计5-10个工作日",
				"fit":"男士",
				"color1":"蓝色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"**皮",
				"desc":"藏蓝色皮质材质，方形美杜莎银色金属扣",
				"story":'VERSACE JEANS COUTURE是VERSACE的二线比较年轻的副牌，价格也比VERSACE低很多。迎合了时尚人士渴望在各个场合中都能展现自我个性的需求。',
				"logoBg":"../img/screen/b6/bd.jpg"
			},
		"m6":{
				"sider":["../img/screen/m6/1.jpg","../img/screen/m6/2.jpg","../img/screen/m6/3.jpg","../img/screen/m6/4.jpg","../img/screen/m6/5.jpg"],
				"brand":"Versace 范思哲",
				"info":"牛皮 男仕 腰带",
				"price":"￥3190.00",
				"color":"#3369EB",
				"size":["100","105","90","95"],
				"num":"273321",
				"goosNum":"DCU4949 DVTP1 K8BOH_245 ",
				"address":"-",
				"year":"-",
				"time":"该商品到货时间预计5-10个工作日",
				"fit":"男士",
				"color1":"蓝色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"牛皮",
				"desc":"藏蓝色皮质材质，金属腰带扣",
				"story":'品牌标志是神话中的蛇妖美杜莎（Medusa），代表着致命的吸引力。范思哲的设计风格非常鲜明，独特的美感、极强的先锋艺术表征让他**，他强调快乐与性感，领口常开到腰部以下，拮取了古典贵族风格的豪华、奢丽，又能充分考虑穿着舒适及恰当的显示体型。范思哲善于采用高贵豪华的面料，借助斜裁方式，在生硬的几何线条与柔和的身体曲线间巧妙过渡，范思哲的套装、裙子、大衣等都以线条为标志，性感地表达女性的身体。范思哲还经营香水、眼镜、领带、皮件、包袋、瓷器、玻璃器皿、丝巾、羽绒制品、家具产品等。',
				"logoBg":"../img/screen/m6/bd.jpg"
			},
		"m7":{
				"sider":["../img/screen/m7/1.jpg","../img/screen/m7/2.jpg","../img/screen/m7/3.jpg","../img/screen/m7/4.jpg","../img/screen/m7/5.jpg"],
				"brand":"Raf Simons",
				"info":"棉质 男士 棒球帽",
				"price":"￥1380.00",
				"color":"#2A2A2A",
				"size":["无"],
				"num":"338762",
				"goosNum":"raf0130026brm",
				"address":"意大利",
				"year":"2017",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"黑色",
				"season":"秋冬新款",
				"serise":"-",
				"mateirs":"99%棉质",
				"desc":"只能干洗",
				"story":'顶风取代 John Galliano 出任 Dior 主设计师的 Raf Simons 自己的品牌包括 Raf Simons 和副线 Raf by Raf Simons，他亦曾是Jil Sander的首席设计师。RafSimons**初学习工业设计，通过自学接触服装设计。1995年， Raf Simons 创建了自己的品牌，受工业设计学习经历的影响，充满了鲜明的建构感和极简主义风格，他**擅长的就是利落的单线条的运用。他的男装设计以前卫、“革命性”著称。纽约时报曾评价他为“几乎是上世纪**影响力的男装设计师”。2012年2月25日，米兰2012秋冬时装周 Raf Simons **一次作为Jil Sander首席设计师登台谢幕。2012年4月，LVMH 集团公布消息，Raf Simons 将接替 Bill Gaytten 执掌Dior，并于巴黎时间4月9日宣布 Raf Simons 取代 John Galliano 出任 Dior 总设计师',
				"logoBg":"../img/screen/m2/bd.jpg"
			},
		"m8":{
				"sider":["../img/screen/m8/1.jpg","../img/screen/m8/2.jpg","../img/screen/m8/3.jpg","../img/screen/m8/4.jpg"],
				"brand":"Cartier 卡地亚",
				"info":"镀铂金合金 哑光半框 光学镜架",
				"price":"￥6100.00",
				"color":"#D3D3D3",
				"size":["无"],
				"num":"89901",
				"goosNum":"T8100871",
				"address":"法国",
				"year":"-",
				"time":"该商品到货时间预计5-10个工作日",
				"fit":"男士",
				"color1":"银色",
				"season":"-",
				"serise":"-",
				"mateirs":"镀铂金合金/复合板材",
				"desc":"镀铂金合金材质 半框设计 茶色板材镜腿",
				"story":'卡地亚 (Cartier) 是珠宝界知名度**、历史**悠久的品牌之一，卡地亚 (Cartier)也是**受贵族明星喜爱的珠宝品牌。无论**珠宝还是腕表系列，卡地亚 (Cartier) 都本着出色的制作工艺、专业技术和独特风格，传递着专属其品牌的高贵价值',
				"logoBg":"../img/screen/m8/bd.jpg"
			},
		"m9":{
				"sider":["../img/screen/m9/1.jpg","../img/screen/m9/2.jpg","../img/screen/m9/3.jpg"],
				"brand":"Louis Vuitton 路易威登",
				"info":"皮革 男仕 啡色印花皮带（95cm）",
				"price":"￥4400.00",
				"color":"#A47456",
				"size":["无"],
				"num":"128782",
				"goosNum":"M9821T_252",
				"address":"-",
				"year":"2011",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"棕色",
				"season":"-",
				"serise":"-",
				"mateirs":"皮革",
				"desc":"注意事项：该商品不允许使用优惠券",
				"story":'路易·威登 (Louis Vuitton) 高度尊重和珍视自己的品牌。品牌不仅以其创始人路易·威登 (Louis Vuitton) 的名字命名，也继承了他追求品质、精益求精的态度。路易·威登 (Louis Vuitton) 的另一个成功秘诀就是力求为尊贵的顾客营造一种“家庭”的感觉，可以代代相传。',
				"logoBg":"../img/screen/m9/bd.jpg"
			},
		"m10":{
				"sider":["../img/screen/m10/1.jpg","../img/screen/m10/2.jpg","../img/screen/m10/3.jpg","../img/screen/m10/4.jpg"],
				"brand":"Louis Vuitton 路易威登",
				"info":"皮革 男仕 啡色印花皮带（90cm）",
				"price":"￥3700.00",
				"color":"#A47456",
				"size":["无"],
				"num":"128776",
				"goosNum":"M9807T_252",
				"address":"-",
				"year":"2016",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"棕色",
				"season":"-",
				"serise":"-",
				"mateirs":"牛皮",
				"desc":"注意事项：该商品不允许使用优惠券",
				"story":'路易·威登 (Louis Vuitton) 高度尊重和珍视自己的品牌。品牌不仅以其创始人路易·威登 (Louis Vuitton) 的名字命名，也继承了他追求品质、精益求精的态度。路易·威登 (Louis Vuitton) 的另一个成功秘诀就是力求为尊贵的顾客营造一种“家庭”的感觉，可以代代相传。',
				"logoBg":"../img/screen/m9/bd.jpg"
			},
		"m11":{
				"sider":["../img/screen/m11/1.jpg","../img/screen/m11/2.jpg","../img/screen/m11/3.jpg","../img/screen/m11/4.jpg"],
				"brand":"Dior 迪奥",
				"info":"小牛皮 男士 皮带",
				"price":"￥3480.00",
				"color":"#2E2E2E",
				"size":["100","105","90","95"],
				"num":"303055",
				"goosNum":"4166PLXJLH02G",
				"address":"意大利",
				"year":"2017",
				"time":"该商品到货时间预计15-20个工作日，具体时间受海关放行效率影响",
				"fit":"男士",
				"color1":"黑色",
				"season":"-",
				"serise":"-",
				"mateirs":"小牛皮",
				"desc":"尺码：  带体2.5   颜色：黑色  材质：小牛皮   描述：涂层帆布和黑色小牛皮，可调节带头",
				"story":'Dior迪奥，由法国时装设计师克丽斯汀·迪奥（Christian Dior）于1946年创于巴黎，半个多世纪以来，品牌设计不断创新却始终保持着高贵优雅的风格和品位，演绎时尚魅惑，自信活力。在时装、珠宝及手表、香水、彩妆和护肤领域，迪奥是优雅、**与奢华的**呈现。',
				"logoBg":"../img/screen/p1/bd.jpg"
			},
		"m12":{
				"sider":["../img/screen/m12/1.jpg","../img/screen/m12/2.jpg","../img/screen/m12/3.jpg","../img/screen/m12/4.jpg","../img/screen/m12/5.jpg"],
				"brand":"Versace Collection 范思哲系列",
				"info":"17春夏新款 皮质 男仕 双面腰带",
				"price":"￥1540.00",
				"color":"#4271E6",
				"size":["100","105","90","95"],
				"num":"286455",
				"goosNum":"V910190 VM00043 V366V_245 ",
				"address":"-",
				"year":"-",
				"time":"该商品到货时间预计5-10个工作日",
				"fit":"男士",
				"color1":"蓝色",
				"season":"-",
				"serise":"-",
				"mateirs":"**皮",
				"desc":"深蓝色皮质材质，银色板扣，双面腰带款式",
				"story":'VersaceCollection是全球知名**品集团Versace（范思哲）旗下**成衣品牌，品牌定位为25岁~35岁的女性。2009 年，在创意总监Donatella Versace的带领下，Versace Collection女装系列正式诞生。该品牌服装和配饰拥有毋庸置疑的品质和强烈的时尚感，相比于Versace**时装系列，Versace Collection少了几分浮夸，多了几分高雅，更适宜日常穿着。利落的剪裁雕塑出女性柔美的线条，微妙的细节处理满足了那些想要打扮得时尚而且充满个性，入时而又迷人。',
				"logoBg":"../img/screen/b6/bd.jpg"
			},



	"s11":{
			"sider":["../img/screen/s11/1.jpg","../img/screen/s11/2.jpg","../img/screen/s11/3.jpg","../img/screen/s11/4.jpg","../img/screen/s11/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"WIFI眼 男士 卫衣",
			"price":"￥1190.00",
			"color":"#2963E9",
			"size":["46","48","50","52"],
			"num":"336631",
			"goosNum":"FMCF7014FE ",
			"address":"土耳其",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"蓝色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"棉",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：正面WIFI 眼设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s22":{
			"sider":["../img/screen/s22/1.jpg","../img/screen/s22/2.jpg","../img/screen/s22/3.jpg","../img/screen/s22/4.jpg","../img/screen/s22/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"WIFI眼 男士 卫衣",
			"price":"￥1190.00",
			"color":"#969696",
			"size":["46","48","50","52"],
			"num":"336634",
			"goosNum":"FMCF7014FE ",
			"address":"土耳其",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"灰色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"棉",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：正面WIFI 眼设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s33":{
			"sider":["../img/screen/s33/1.jpg","../img/screen/s33/2.jpg","../img/screen/s33/3.jpg","../img/screen/s33/4.jpg","../img/screen/s33/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"金龟子图案金银丝勾花羊毛衫",
			"price":"￥1790.00",
			"color":"#969696",
			"size":["46","48","50","52"],
			"num":"337870",
			"goosNum":"FMCF7084FE ",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"白色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"羊毛-锦纶",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：1.含毛类面料会有轻微气球，属正常现象，保养时需并放置防虫和防蛀药剂，自行洗涤有困难请送专业洗衣店洗涤。2.避免长时间穿着，避免烈日暴晒。3.注意别溅着火星，避免沾上有化学作用的物体和液体，避免硬物摩擦和尖物勾丝、勾破（包括包包、首饰、指甲等）	设计特色：正面金龟子图案金银丝勾花设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s44":{
			"sider":["../img/screen/s44/1.jpg","../img/screen/s44/2.jpg","../img/screen/s44/3.jpg","../img/screen/s44/4.jpg","../img/screen/s44/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"科技印花长袖连帽开衫卫衣",
			"price":"￥2590.00",
			"color":"#A3A3A3",
			"size":["46","48","50","52"],
			"num":"336597",
			"goosNum":"FMCF7078FE ",
			"address":"土耳其",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"灰色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"棉",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：科技印花设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s55":{
			"sider":["../img/screen/s55/1.jpg","../img/screen/s55/2.jpg","../img/screen/s55/3.jpg","../img/screen/s55/4.jpg","../img/screen/s55/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"科技印花夹棉男士运动短夹克",
			"price":"￥5390.00",
			"color":"#5A5058",
			"size":["46","48","50"],
			"num":"337600",
			"goosNum":"FMCF7134BM ",
			"address":"意大利",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"多色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"聚酯纤维",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：科技印花设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s66":{
			"sider":["../img/screen/s66/1.jpg","../img/screen/s66/2.jpg","../img/screen/s66/3.jpg","../img/screen/s66/4.jpg","../img/screen/s66/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"机械羽翼休闲卫衣",
			"price":"￥1690.00",
			"color":"#2A2A2A",
			"size":["46","48","50","52"],
			"num":"336607",
			"goosNum":"FMCF7013FE ",
			"address":"土耳其",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"黑色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"棉",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：两侧机械羽翼，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s77":{
			"sider":["../img/screen/s77/1.jpg","../img/screen/s77/2.jpg","../img/screen/s77/3.jpg","../img/screen/s77/4.jpg","../img/screen/s77/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"印花图腾羊毛衫",
			"price":"￥1690.00",
			"color":"#B2C86E",
			"size":["46","48","50","52"],
			"num":"337937",
			"goosNum":"FMCF7086MA",
			"address":"中国",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"绿色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"羊毛",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：1.含毛类面料会有轻微气球，属正常现象，保养时需并放置防虫和防蛀药剂，自行洗涤有困难请送专业洗衣店洗涤。2.避免长时间穿着，避免烈日暴晒。设计特色：正面图腾设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},
	"s88":{
			"sider":["../img/screen/s88/1.jpg","../img/screen/s88/2.jpg","../img/screen/s88/3.jpg","../img/screen/s88/4.jpg","../img/screen/s88/5.jpg"],
			"brand":"Frankie Morello 弗兰基.莫雷诺",
			"info":"全印花长袖开衫卫衣",
			"price":"￥2490.00",
			"color":"#DA7473",
			"size":["46","48","50","52"],
			"num":"337623",
			"goosNum":"FMCF7023FE ",
			"address":"土耳其",
			"year":"2017",
			"time":"该商品到货时间预计3-5个工作日",
			"fit":"男士",
			"color1":"多色",
			"season":"秋冬新款",
			"serise":"FM男装",
			"mateirs":"棉",
			"desc":"男士上衣48码尺寸：胸围95-98 腰围：81-84 衣长：171-175 注意事项：单独洗涤，反面晾干	设计特色：全印花设计，体感舒适，易搭配",
			"story":'意大利成衣品牌FRANKIEMORELLO作为每季都参加米兰时装周的品牌来说，无论设计、制作、价格来说都是一线水准。FRANKIE MORELLO既有意大利式的时尚，热情，奔放；也透露着些许MOSCHINO式的夸张，搞笑和戏谑，同时两位设计师也极富童真，不时将卡通元素融入其中。FRANKIE MORELLO男人装设计面料确保舒适度和弹性，融合运动、休闲与时尚，穿着舒适，与潮流巧妙的结合，营造男人的运动时尚视觉，让男人个性十足，魅力四射。',
			"logoBg":"../img/screen/s11/bd.jpg"
		},



	};
	



	
}])